version: "3.5"

name: wetterserver

services:
  wetterserver:
    build:
      dockerfile: Dockerfile
      #target: release-stage
    container_name: wetterserver
    volumes:
        - "weatherserver_data:/db"
    networks:
     - homeserver
    environment:
      - "TZ=Europe/Paris"
    restart: always
    labels:
      - "traefik.http.routers.wetterserver.rule=Host(`wetterserver.homeserver.lan`)"
      - "traefik.http.middlewares.testheader.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
      - "traefik.http.middlewares.testheader.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.testheader.headers.accesscontrolalloworiginlist=http://wetterdashboard.homeserver.lan,http://localhost:49430"
      - "traefik.http.middlewares.testheader.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.testheader.headers.addvaryheader=true"

volumes:
  weatherserver_data:
    name: weatherserver_data

networks:
  homeserver:
    external: true