version: "3.5"

name: melderserver

services:
  melderserver:
    build:
      dockerfile: Dockerfile
      target: release-stage
      args:
        - GITUSER=${GITUSER}
        - GITTOKEN=${GITTOKEN}
    container_name: melderserver
    networks:
      - homeserver
    volumes:
        - "melderserver_data:/db"
    environment:
      - "TZ=Europe/Berlin"
    devices:
     - "/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0"
    restart: always
    labels:
      - "traefik.http.routers.melderserver.rule=Host(`melderserver.homeserver.lan`)"


volumes:
  melderserver_data:
    name: melderserver_data

networks:
  homeserver:
    external: true